// Generates src/generated/ from ../contract/surface.json, and nothing else. Two files:
//
//   contract.ts - types only, from openapi-typescript. Nothing at run time comes from a generator,
//                 so nothing at run time can drop a field the contract carries.
//   surface.ts  - the derived operation table, the contract's version and checksum, and the error
//                 codes the covered surface documents, as constants the SDK imports rather than
//                 retypes.
//
//   node scripts/generate.mjs          # write
//   node scripts/generate.mjs --check  # exit 1 if src/generated/ is not what the surface generates

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

const here = dirname(fileURLToPath(import.meta.url));
const SURFACE = join(here, '..', '..', 'contract', 'surface.json');
const OUT = join(here, '..', 'src', 'generated');

const surfaceText = readFileSync(SURFACE, 'utf8');
const surface = JSON.parse(surfaceText);
const derived = surface['x-atlas-derived'];
const generator = JSON.parse(
  readFileSync(join(here, '..', 'node_modules', 'openapi-typescript', 'package.json'), 'utf8'),
).version;

const banner = [
  `// Generated by scripts/generate.mjs from contract/surface.json - contract ${derived.from.version},`,
  `// sha256 ${derived.from.sha256} - with openapi-typescript ${generator}. Do not edit: change the`,
  '// contract, vendor it, derive the surface and run `npm run generate`.',
  '',
].join('\n');

const types = banner + astToString(await openapiTS(surface));

const serverPath = new URL(surface.servers?.[0]?.url ?? '/', 'https://server.invalid').pathname.replace(
  /\/$/,
  '',
);
const errorCodes = [...new Set(surfaceText.match(/ATLAS-[A-Z]+-\d{3}/g) ?? [])].sort();
const operations = Object.fromEntries(
  derived.operations.map(({ operationId, ...rest }) => [operationId, rest]),
);

const constants =
  banner +
  [
    '/** The contract this SDK was generated from. */',
    `export const CONTRACT = ${JSON.stringify(derived.from)} as const;`,
    '',
    "/** The path every operation is relative to, from the contract's `servers` entry. */",
    `export const SERVER_PATH = ${JSON.stringify(serverPath)};`,
    '',
    '/** The schemes a developer credential is sent under. */',
    `export const DEVELOPER_SCHEMES = ${JSON.stringify(derived.developerSchemes)} as const;`,
    '',
    '/**',
    ' * Every operation this SDK covers, derived from the contract by one rule: every operation whose',
    " * `security` admits a developer credential, plus the operation a developer credential's scheme",
    ' * names in `x-atlas-issued-by`.',
    ' */',
    `export const OPERATIONS = ${JSON.stringify(operations, null, 2)} as const;`,
    '',
    '/** Every `errorCode` the covered surface documents. */',
    `export const ERROR_CODES = ${JSON.stringify(errorCodes, null, 2)} as const;`,
    '',
  ].join('\n');

const files = { 'contract.ts': types, 'surface.ts': constants };

if (process.argv.includes('--check')) {
  const stale = Object.entries(files).filter(([name, text]) => {
    try {
      return readFileSync(join(OUT, name), 'utf8').replace(/\r\n/g, '\n') !== text;
    } catch {
      return true;
    }
  });
  if (stale.length) {
    console.error(
      `generate: src/generated/${stale.map(([name]) => name).join(' and ')} not what the surface generates. ` +
        'Run: npm run generate',
    );
    process.exit(1);
  }
  console.log(`generate: src/generated/ is current for contract ${derived.from.version}.`);
} else {
  mkdirSync(OUT, { recursive: true });
  for (const [name, text] of Object.entries(files)) writeFileSync(join(OUT, name), text);
  console.log(
    `generate: wrote src/generated/ - ${derived.operations.length} operations, ${errorCodes.length} error codes, ` +
      `contract ${derived.from.version}.`,
  );
}
