# Generated by scripts/generate.py from contract/surface.json - contract 1.7.0,
# sha256 c86ec2657cd5a850befd8cc0f7e7b746d3ae3d66fe45dd85727ca09e2804d6ec - with datamodel-code-generator 0.83.0.
# Do not edit: change the contract, vendor it, derive the surface and run
# `uv run python scripts/generate.py`.

from typing import Literal, NotRequired, TypedDict

type ApiScope = Literal[
    "content:read",
    "content:write",
    "profiles:read",
    "ai:use",
    "search:use",
    "end-users:manage",
    "webhooks:manage",
    "usage:read",
]


class ResourceWebhookEventData(TypedDict):
    """
    Ids, and one closed vocabulary. No title, no file name, no parser output: this body leaves ATLAS for a machine on the public internet, and nothing derived from an uploaded document travels without a reason. Read the rest with `getResource`, authenticated, under your own scope.

    """

    resource_id: str
    version_id: str
    reason: NotRequired[str]


class TokenExchangeRequest(TypedDict):
    """
    A code exchange, or a renewal. Called by your server; there is no client secret, and PKCE binds the exchange instead.

    """

    grantType: Literal["authorization_code", "refresh_token"]
    code: NotRequired[str]
    redirectUri: NotRequired[str]
    codeVerifier: NotRequired[str]
    refreshToken: NotRequired[str]
    clientId: str


class DelegatedPassResponse(TypedDict):
    """
    A delegated pass and its renewal secret (RFC 6749 §5.1). The field names are RFC 6749's rather than this document's usual camelCase, because these are the names every OAuth2 client expects to read off a token response.

    """

    access_token: str
    token_type: Literal["Bearer"]
    expires_in: int
    refresh_token: str
    scope: str


class LinkEndUserRequest(TypedDict):
    """
    Link one of your own learners. **You are the data controller for this person and ATLAS is your processor**, which is why the only thing this carries is your own reference for them.

    ATLAS hashes `ref` and stores the digest. The value itself is never persisted, never logged and never returned - there is no field on any response that could carry it back, and no request that can retrieve it. Send whatever identifier your own system already uses; ATLAS neither needs nor wants to know what it means.

    """

    ref: str


class EndUserResponse(TypedDict):
    """
    A linked end user. Carries no `ref`, and could not: ATLAS holds only a digest of it.

    """

    id: str
    appId: str
    active: bool
    linkedAt: str
    revokedAt: NotRequired[str | None]


class EndUserPage(TypedDict):
    """
    A page of end users (the `{items, nextCursor}` paging envelope). Null `nextCursor` means there is no next page.

    """

    items: list[EndUserResponse]
    nextCursor: str | None


class DeveloperAppUsage(TypedDict):
    """
    One application's metered activity over the period
    """

    appId: str | None
    name: NotRequired[str | None]
    calls: int
    tokens: int


class DeveloperRateLimitStanding(TypedDict):
    """
    Where this account stands against its request budget. Reading it does not spend it.

    """

    limit: int
    remaining: int
    resetSeconds: int


type DeveloperUsageState = Literal["WITHIN_LIMITS", "THROTTLED"]


class DeveloperUsageResponse(TypedDict):
    """
    API usage for a developer account. **Carries no figure denominated in money** - commercial data is the account Admin's alone, and it is served by a separate operation this one cannot reach. Operational allowance state is not commercial data, so every role reads this, and so does a key holding `usage:read`.

    Two usage panels are absent. **Errors** needs a queryable record of failed requests and ATLAS mints none today; it is tracked and will arrive as an additive change.

    """

    periodStart: str
    periodEnd: str
    calls: int
    apps: list[DeveloperAppUsage]
    rateLimit: NotRequired[DeveloperRateLimitStanding]
    state: DeveloperUsageState


class KeyIdentityResponse(TypedDict):
    """
    Who an API key is, and what it may do. It discloses nothing the caller did not already hold - no names, no members, no content, and no permission the presented key does not itself carry - so a stolen key is not also a way to learn about the account it came from.

    This is where a `403 ATLAS-SYS-007` is diagnosed: that refusal names the scope it wanted and deliberately never names what your key holds, so the two halves of the answer come from different places and only the holder can put them together.

    """

    keyId: str
    appId: str
    orgId: str
    keyPrefix: str
    last4: str
    scopes: list[ApiScope]
    expiresAt: NotRequired[str | None]


class ResourceDownloadResponse(TypedDict):
    """
    A short-lived URL for a resource's original file. Returned as a URL in a JSON body rather than a redirect, so the browser never follows a cross-origin redirect with credentials attached and the screen can surface a failure as a message.

    """

    downloadUrl: str
    expiresAt: str
    filename: str


class ResourceResponse(TypedDict):
    """
    A resource's state - its identity plus the state of its DISPLAY version (the current one when set, else its latest) flattened in, so the library and detail surfaces read one object per resource. `status`, `sizeBytes`, `contentType`, and `originalFilename` describe the display version; `versionCount` is the whole timeline's length.

    The bytes' `fingerprint` is deliberately NOT here. It would be harmless as a per-org detail - a member who can list a resource can download it and hash it themselves - but it is the platform-wide key that content-addressed reuse is decided on, and a stable cross-org content identifier on a bulk listing lets two members in DIFFERENT orgs establish that both orgs hold the same file, byte for byte. That is what ATLAS refuses to let anyone learn by timing, reached another way.

    """

    id: str
    title: str
    status: Literal["AWAITING_UPLOAD", "SCANNING", "READING", "BUILDING", "READY", "FAILED"]
    failureReason: NotRequired[
        Literal[
            "TOO_LARGE",
            "INFECTED",
            "ARCHIVE_LIMITS",
            "SCAN_REQUIRED",
            "UPLOAD_ABANDONED",
            "UPLOAD_MISMATCHED",
            "EXTRACT_FAILED",
            "BLOCKED",
            "INGEST_ABANDONED",
        ]
        | None
    ]
    sizeBytes: NotRequired[int | None]
    contentType: NotRequired[str | None]
    originalFilename: NotRequired[str | None]
    versionId: str
    versionNumber: int
    versionCount: int
    createdAt: str
    updatedAt: str
    deletedAt: NotRequired[str | None]


class MultiCategoryScore(TypedDict):
    structureType: Literal["multi-category"]
    categories: dict[str, float]
    dominantCategory: str


class BipolarScore(TypedDict):
    structureType: Literal["bipolar"]
    score: float
    scorePercent: float
    poleALabel: str
    poleBLabel: str


class AttentionChecksSummary(TypedDict):
    """
    The validity signal from the sitting's attention checks. It is not a score and changes nothing - a respondent who fails every check still gets exactly the profile their answers produce.

    """

    passed: int
    failed: int
    presented: int


class PresentationPlan(TypedDict):
    """
    What the reader should do differently for this learner, with no AI and no wait. Always present and never null: every option carries an explicit baseline value, so "the profile has no view" is a state the plan states rather than one a client infers from absence.

    **Only `figures` is rendered today.** The rest carry the learner's preference and are applied by nobody yet - `chunking` and `navigation` need a reader surface that does not exist yet, and `tableOfContents` and `panels` are simply unconsumed. No feature family gates them - F2, F3, F6 and F10 are all live; nothing reads them.

    `panels` stays unrendered by decision rather than by omission: Zone 7 is its own route, and the reader's utility rail is exactly three tabs with no social panel in it, so wiring a fourth from this value would build a surface the reader does not have. A value here is what the learner prefers, not permission to show it: whoever renders one applies its gate at that point.

    **Disagreement resolves to the baseline.** Presentation options are not additive - a chunk is either small or whole - so where two endorsed categories disagree the presenter applies neither. The reasoning is a research one: a precedence rule invented in code would rank learner profiles against one another in a way the research never does.

    """

    figures: Literal["figures-first", "source-order"]
    chunking: Literal["small-segments", "whole-document", "source-default"]
    navigation: Literal["guided", "free", "source-order"]
    tableOfContents: Literal["offered", "suppressed", "source-default"]
    panels: Literal["offered", "suppressed", "source-default"]


class EndorsedCategory(TypedDict):
    """
    One preference the learner expressed, and what it recommends - grouped per category.

    """

    key: str
    dimension: str
    label: str
    strength: float
    weight: float
    families: list[str]


class FeatureReason(TypedDict):
    """
    Why a family was recommended - the preference that asked for it
    """

    key: str
    label: str
    strength: float
    weight: float


class ProfileAppearanceDefaults(TypedDict):
    """
    Look-and-feel settings the profile SUGGESTS - defaults, never saved choices. `/appearance/preferences` stays the record of what the person actually chose; resolve explicit choice, then these, then the client's own default. A field the profile says nothing about is OMITTED, never sent as null - the same convention `/appearance/preferences` uses, so a client resolving the layers reads one shape rather than two. Most settings are always absent: no sub-dimension measures text size, line spacing or reading face.

    """

    theme: NotRequired[Literal["light", "dark", "high-contrast", "system"]]
    focusMode: NotRequired[bool]


class Error(TypedDict):
    field: NotRequired[str]
    code: NotRequired[str]
    message: NotRequired[str]


class Problem(TypedDict):
    """
    Problem details (RFC 9457, `application/problem+json`), the one shape every refusal in this API takes.

    **Branch on `errorCode`.** It is present on every refusal (the API description names the one malformed path the web server refuses first), it names one cause exactly, every value is documented in this contract - on the operations that can answer it, or in the API description for the few that any operation can - and a value is never removed or reused once published. A new value is a minor version of this contract. `type` is coarser: two causes can share one - `not-found` covers both a missing record and an organisation that is not a developer account - so a client branching on `type` would treat them alike.

    **`type` is an identifier, not a link.** It is a URI under `https://atlasframework.dev/problems/`, stable for as long as its code is, and fine to compare and to log. Do not dereference it: no page is published at those addresses yet.

    Validation refusals add an `errors` array naming each field; an unexpected `500` adds an `errorId`, which is what to quote when reporting it.

    """

    type: str
    title: str
    status: int
    detail: NotRequired[str]
    errorCode: NotRequired[str]
    errorId: NotRequired[str]
    errors: NotRequired[list[Error]]


class ResourceWebhookEvent(TypedDict):
    """
    The body of every message ATLAS sends you.

    ## Verifying it

    Every request carries an `ATLAS-Signature` header:

    `t=1758499200,v1=5a3f...`

    where `t` is a Unix timestamp in seconds and each `v1` is a lower-case hex HMAC-SHA256. To verify:

    1. Read the RAW request body as bytes, before any JSON parsing. Parsing
       and re-serialising will change the bytes and the signature will not
       match.

    2. Split the header on `,` and read the `t=` value and every `v1=` value.
       There can be MORE THAN ONE `v1` - see rotation below.

    3. Build the signed string as `t + "." + body` - the timestamp, a single
       full stop, then the raw body.

    4. Compute `HMAC-SHA256(secret, signedString)` with your endpoint's
       signing secret and render it as lower-case hex.

    5. Compare it against each `v1` using a CONSTANT-TIME comparison. If any
       matches, the message is authentic.

    6. Check that the `t` WHICH PRODUCED THE MATCH is within 300 seconds of
       your own clock. Use that one, not the last `t` you parsed - a header
       can carry more than one, and checking the freshness of a different
       timestamp from the one you verified defeats the window entirely.


    ## Rotation

    When you rotate a signing secret, ATLAS signs with the new secret AND the old one for the overlap window, sending two `v1` values. A verifier that tries every `v1` until one matches - step 5 above - keeps working throughout. A verifier that checks only the first will reject roughly half of what arrives during the window.

    ## Delivery is at-least-once, and `delivery_id` is how you deduplicate

    **You may receive the same message more than once.** That is expected rather than a fault: ATLAS retries a delivery whose outcome it did not observe, and a process that died after your server answered is indistinguishable from one that died before. Exactly-once delivery across a network is not available, and this contract says so rather than implying otherwise.

    `delivery_id` is stable for the life of a delivery. Every retry, and every replay you trigger from the webhooks screen, carries the SAME value. Record it and ignore a message whose `delivery_id` you have already processed, and duplicates cost you nothing.

    It is inside the signed body, so it cannot be forged or stripped in transit. The `ATLAS-Delivery-Attempt` header carries the attempt number as a convenience for your logs; it is OUTSIDE the signature, so do not make a decision on it.

    `event_id` identifies the OCCURRENCE. If you registered two endpoints that feed one system, both will receive the same `event_id` with different `delivery_id`s - deduplicate on `event_id` in that case.

    ## Ordering

    Nothing is promised. A retried `resource.ready` can arrive after the `resource.updated` that superseded it, because a failed delivery waits out its backoff while later ones go straight through. Use `occurred_at`.

    ## Answering

    Any 2xx means accepted. ATLAS waits ten seconds and follows no redirects, so answer as soon as you have durably recorded the message and do the work afterwards. A failure is retried with exponential backoff; after eight attempts the delivery is abandoned and shows in your delivery log, and after five consecutive abandoned deliveries ATLAS stops calling the endpoint until somebody re-enables it.

    """

    delivery_id: str
    event_id: str
    type: Literal["resource.ready", "resource.updated", "resource.failed"]
    occurred_at: str
    data: ResourceWebhookEventData


class ResourceListResponse(TypedDict):
    """
    One page of the org's resource library, with the totals pagination controls need.

    """

    items: list[ResourceResponse]
    page: int
    size: int
    totalItems: int
    totalPages: int


type SubDimensionScore = MultiCategoryScore | BipolarScore


class RecommendedFeature(TypedDict):
    """
    One feature family placed in this learner's recommendation order.

    """

    rank: int
    code: str
    label: str
    kind: Literal["GENERAL", "AI"]
    usesModel: bool
    delivery: Literal["LIVE", "PLANNED"]
    score: float
    autoEnabled: bool
    override: NotRequired[bool]
    enabled: bool
    reasons: list[FeatureReason]


class LearnerProfile(TypedDict):
    """
    A learner's scored profile. Personal data in the most private tier - never visible to an org in any form. Returned from the stored answers on every read, with no stored copy to go stale; sent by a developer to `presentForEndUser`, where it is held to the instrument and to the bounds below.

    """

    taxonomyVersion: str
    completedDimensions: list[str]
    categoryScores: dict[str, float]
    percentScores: dict[str, float]
    subDimensionScores: dict[str, SubDimensionScore]
    attentionChecks: AttentionChecksSummary


class PersonalisationProfile(TypedDict):
    """
    What ATLAS personalises for one learner, and why. Private to the learner, derived on every read and stored nowhere.

    """

    taxonomyVersion: str
    signature: NotRequired[str]
    completedDimensions: list[str]
    endorsements: list[EndorsedCategory]
    features: list[RecommendedFeature]
    appearanceDefaults: ProfileAppearanceDefaults
    presentation: PresentationPlan


class PresentEndUserRequest(TypedDict):
    """
    A personalised read for a linked end user.

    **The profile comes with the request, every time.** ATLAS stores no profile for an end user - a learner profile is derived from stored questionnaire answers, and an end user has no ATLAS account to hold any - so this is the input rather than a lookup key. That is also what keeps a retake instant on this surface: there is no cached copy to invalidate, because there is no copy.

    """

    profile: LearnerProfile
