# Generated by scripts/generate.py from contract/surface.json - contract 1.7.0,
# sha256 c86ec2657cd5a850befd8cc0f7e7b746d3ae3d66fe45dd85727ca09e2804d6ec - with datamodel-code-generator 0.83.0.
# Do not edit: change the contract, vendor it, derive the surface and run
# `uv run python scripts/generate.py`.
"""The operations this SDK covers, and the contract they were derived from."""

from dataclasses import dataclass
from types import MappingProxyType
from typing import Final, Literal


@dataclass(frozen=True, slots=True)
class Contract:
    """The contract this SDK was generated from."""

    version: str
    sha256: str


@dataclass(frozen=True, slots=True)
class Operation:
    """One operation, as the contract describes it."""

    method: str
    path: str
    credentials: tuple[str, ...]
    scopes: MappingProxyType[str, tuple[str, ...]]
    issues: str | None
    idempotency_key: bool
    retry: Literal["repeatable", "repeatable-with-key", "once"]
    path_params: tuple[str, ...]
    query_params: tuple[str, ...]


CONTRACT: Final = Contract(
    version="1.7.0", sha256="c86ec2657cd5a850befd8cc0f7e7b746d3ae3d66fe45dd85727ca09e2804d6ec"
)
"""The contract this SDK was generated from."""

SERVER_PATH: Final = "/v1"
"""The path every operation is relative to, from the contract's `servers` entry."""

DEVELOPER_SCHEMES: Final = ("apiKeyAuth", "delegatedPassAuth")
"""The schemes a developer credential is sent under."""

type OperationId = Literal[
    "describeKey",
    "exchangeDelegatedToken",
    "listEndUsers",
    "linkEndUser",
    "revokeEndUser",
    "presentForEndUser",
    "developerUsage",
    "listResources",
    "getResourceDownload",
    "getResource",
]

OPERATIONS: Final[MappingProxyType[OperationId, Operation]] = MappingProxyType(
    {
        "describeKey": Operation(
            method="GET",
            path="/key",
            credentials=("apiKeyAuth",),
            scopes=MappingProxyType({"apiKeyAuth": ()}),
            issues=None,
            idempotency_key=False,
            retry="repeatable",
            path_params=(),
            query_params=(),
        ),
        "exchangeDelegatedToken": Operation(
            method="POST",
            path="/oauth/token",
            credentials=(),
            scopes=MappingProxyType({}),
            issues="delegatedPassAuth",
            idempotency_key=False,
            retry="once",
            path_params=(),
            query_params=(),
        ),
        "listEndUsers": Operation(
            method="GET",
            path="/o/{orgId}/end-users",
            credentials=("apiKeyAuth",),
            scopes=MappingProxyType({"apiKeyAuth": ("end-users:manage",)}),
            issues=None,
            idempotency_key=False,
            retry="repeatable",
            path_params=("orgId",),
            query_params=(),
        ),
        "linkEndUser": Operation(
            method="POST",
            path="/o/{orgId}/end-users",
            credentials=("apiKeyAuth",),
            scopes=MappingProxyType({"apiKeyAuth": ("end-users:manage",)}),
            issues=None,
            idempotency_key=True,
            retry="repeatable-with-key",
            path_params=("orgId",),
            query_params=(),
        ),
        "revokeEndUser": Operation(
            method="DELETE",
            path="/o/{orgId}/end-users/{endUserId}",
            credentials=("apiKeyAuth",),
            scopes=MappingProxyType({"apiKeyAuth": ("end-users:manage",)}),
            issues=None,
            idempotency_key=False,
            retry="repeatable",
            path_params=("orgId", "endUserId"),
            query_params=(),
        ),
        "presentForEndUser": Operation(
            method="POST",
            path="/o/{orgId}/end-users/{endUserId}/present",
            credentials=("apiKeyAuth",),
            scopes=MappingProxyType({"apiKeyAuth": ("ai:use",)}),
            issues=None,
            idempotency_key=False,
            retry="once",
            path_params=("orgId", "endUserId"),
            query_params=(),
        ),
        "developerUsage": Operation(
            method="GET",
            path="/o/{orgId}/dev/usage",
            credentials=("apiKeyAuth",),
            scopes=MappingProxyType({"apiKeyAuth": ("usage:read",)}),
            issues=None,
            idempotency_key=False,
            retry="repeatable",
            path_params=("orgId",),
            query_params=(),
        ),
        "listResources": Operation(
            method="GET",
            path="/o/{orgId}/resources",
            credentials=("apiKeyAuth", "delegatedPassAuth"),
            scopes=MappingProxyType(
                {"apiKeyAuth": ("content:read",), "delegatedPassAuth": ("content:read",)}
            ),
            issues=None,
            idempotency_key=False,
            retry="repeatable",
            path_params=("orgId",),
            query_params=("status", "q", "page", "size"),
        ),
        "getResourceDownload": Operation(
            method="GET",
            path="/o/{orgId}/resources/{resourceId}/download",
            credentials=("apiKeyAuth", "delegatedPassAuth"),
            scopes=MappingProxyType(
                {"apiKeyAuth": ("content:read",), "delegatedPassAuth": ("content:read",)}
            ),
            issues=None,
            idempotency_key=False,
            retry="repeatable",
            path_params=("orgId", "resourceId"),
            query_params=(),
        ),
        "getResource": Operation(
            method="GET",
            path="/o/{orgId}/resources/{resourceId}",
            credentials=("apiKeyAuth", "delegatedPassAuth"),
            scopes=MappingProxyType(
                {"apiKeyAuth": ("content:read",), "delegatedPassAuth": ("content:read",)}
            ),
            issues=None,
            idempotency_key=False,
            retry="repeatable",
            path_params=("orgId", "resourceId"),
            query_params=(),
        ),
    }
)
"""Every operation this SDK covers, derived from the contract by one rule: every
operation whose `security` admits a developer credential, plus the operation a
developer credential's scheme names in `x-atlas-issued-by`.
"""

type KnownErrorCode = Literal[
    "ATLAS-AUTH-005",
    "ATLAS-BIL-001",
    "ATLAS-BIL-002",
    "ATLAS-CNT-008",
    "ATLAS-CNT-016",
    "ATLAS-DEV-001",
    "ATLAS-DEV-009",
    "ATLAS-DEV-010",
    "ATLAS-DEV-011",
    "ATLAS-DEV-012",
    "ATLAS-DEV-014",
    "ATLAS-DEV-020",
    "ATLAS-FRM-010",
    "ATLAS-ORG-002",
    "ATLAS-SYS-001",
    "ATLAS-SYS-002",
    "ATLAS-SYS-003",
    "ATLAS-SYS-004",
    "ATLAS-SYS-005",
    "ATLAS-SYS-007",
    "ATLAS-SYS-008",
    "ATLAS-SYS-009",
    "ATLAS-SYS-010",
    "ATLAS-VAL-001",
    "ATLAS-VAL-002",
    "ATLAS-VAL-003",
]

ERROR_CODES: Final[tuple[KnownErrorCode, ...]] = (
    "ATLAS-AUTH-005",
    "ATLAS-BIL-001",
    "ATLAS-BIL-002",
    "ATLAS-CNT-008",
    "ATLAS-CNT-016",
    "ATLAS-DEV-001",
    "ATLAS-DEV-009",
    "ATLAS-DEV-010",
    "ATLAS-DEV-011",
    "ATLAS-DEV-012",
    "ATLAS-DEV-014",
    "ATLAS-DEV-020",
    "ATLAS-FRM-010",
    "ATLAS-ORG-002",
    "ATLAS-SYS-001",
    "ATLAS-SYS-002",
    "ATLAS-SYS-003",
    "ATLAS-SYS-004",
    "ATLAS-SYS-005",
    "ATLAS-SYS-007",
    "ATLAS-SYS-008",
    "ATLAS-SYS-009",
    "ATLAS-SYS-010",
    "ATLAS-VAL-001",
    "ATLAS-VAL-002",
    "ATLAS-VAL-003",
)
"""Every `errorCode` the covered surface documents."""
