"""Generates src/devatlasframework/sdk/_generated/ from ../contract/surface.json, and nothing else.

Two files:

  contract.py - TypedDicts from datamodel-code-generator, keyed by the names the wire carries.
                They are types only: nothing at run time comes from a generator, so nothing at
                run time can rename or drop a field the contract carries.
  surface.py  - the derived operation table, the contract's version and checksum, and the error
                codes the covered surface documents, as constants the SDK imports rather than
                retypes.

  uv run python scripts/generate.py          # write
  uv run python scripts/generate.py --check  # exit 1 if _generated/ is not what it generates
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from importlib.metadata import version
from pathlib import Path
from typing import Any

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
SURFACE = ROOT.parent / "contract" / "surface.json"
OUT = ROOT / "src" / "devatlasframework" / "sdk" / "_generated"
GENERATOR = "datamodel-code-generator"

# Every flag is explicit, so the output depends on the pinned generator and nothing it defaults.
CODEGEN_FLAGS = [
    "--input-file-type",
    "openapi",
    "--output-model-type",
    "typing.TypedDict",
    "--target-python-version",
    "3.12",
    "--use-standard-collections",
    "--use-union-operator",
    "--enum-field-as-literal",
    "all",
    "--use-schema-description",
    "--use-double-quotes",
    "--disable-timestamp",
    # Without it, `from __future__ import annotations` turns every annotation into a string, and a
    # TypedDict built from strings cannot see `NotRequired`: at run time it would report every key
    # as required, and any tool that introspects the types would refuse a real response.
    "--disable-future-imports",
    "--formatters",
    "builtin",
]


def banner(derived: dict[str, Any]) -> str:
    source = derived["from"]
    return "\n".join(
        [
            "# Generated by scripts/generate.py from contract/surface.json - contract "
            f"{source['version']},",
            f"# sha256 {source['sha256']} - with {GENERATOR} {version(GENERATOR)}.",
            "# Do not edit: change the contract, vendor it, derive the surface and run",
            "# `uv run python scripts/generate.py`.",
        ]
    )


# The generator writes to stdout in the console's code page unless told otherwise, and the
# contract's descriptions carry characters outside ASCII (a Windows console turns "§" into 0xA7).
UTF8 = {**os.environ, "PYTHONUTF8": "1", "PYTHONIOENCODING": "utf-8"}


def ruff_format(text: str, name: str) -> str:
    """Formats generated code with the pinned ruff, under this project's configuration."""
    result = subprocess.run(
        [sys.executable, "-m", "ruff", "format", "--stdin-filename", name, "-"],
        input=text,
        capture_output=True,
        text=True,
        encoding="utf-8",
        env=UTF8,
        cwd=ROOT,
        check=True,
    )
    return result.stdout


def contract_types(derived: dict[str, Any]) -> str:
    result = subprocess.run(
        [
            sys.executable,
            "-m",
            "datamodel_code_generator",
            "--input",
            str(SURFACE),
            *CODEGEN_FLAGS,
            "--custom-file-header",
            banner(derived),
        ],
        capture_output=True,
        text=True,
        encoding="utf-8",
        env=UTF8,
        check=True,
    )
    return ruff_format(result.stdout, "contract.py")


def parameters_of(surface: dict[str, Any], path: str, method: str) -> list[dict[str, Any]]:
    """The parameters an operation declares, its path item's included."""
    item = surface["paths"][path]
    declared = [*item.get("parameters", []), *item[method.lower()].get("parameters", [])]
    for parameter in declared:
        if "$ref" in parameter:
            raise SystemExit(
                f"generate: {path} uses a parameter $ref, which this script cannot read"
            )
    return declared


def surface_constants(surface: dict[str, Any], surface_text: str) -> str:
    derived = surface["x-atlas-derived"]
    server = surface.get("servers", [{}])[0].get("url", "/")
    server_path = "/" + server.strip("/") if server.strip("/") else ""
    error_codes = sorted(set(re.findall(r"ATLAS-[A-Z]+-\d{3}", surface_text)))

    entries = []
    for op in derived["operations"]:
        declared = parameters_of(surface, op["path"], op["method"])
        path_params = tuple(re.findall(r"\{([^}]+)\}", op["path"]))
        query_params = tuple(p["name"] for p in declared if p.get("in") == "query")
        scopes = ", ".join(
            f"{scheme!r}: {tuple(values)!r}" for scheme, values in op["scopes"].items()
        )
        entries.append(
            f"    {op['operationId']!r}: Operation(\n"
            f"        method={op['method']!r},\n"
            f"        path={op['path']!r},\n"
            f"        credentials={tuple(op['credentials'])!r},\n"
            f"        scopes=MappingProxyType({{{scopes}}}),\n"
            f"        issues={op.get('issues')!r},\n"
            f"        idempotency_key={op['idempotencyKey']!r},\n"
            f"        retry={op['retry']!r},\n"
            f"        path_params={path_params!r},\n"
            f"        query_params={query_params!r},\n"
            "    ),"
        )
    operation_ids = ", ".join(repr(op["operationId"]) for op in derived["operations"])
    codes = ", ".join(repr(code) for code in error_codes)

    text = "\n".join(
        [
            banner(derived),
            '"""The operations this SDK covers, and the contract they were derived from."""',
            "",
            "from dataclasses import dataclass",
            "from types import MappingProxyType",
            "from typing import Final, Literal",
            "",
            "",
            "@dataclass(frozen=True, slots=True)",
            "class Contract:",
            '    """The contract this SDK was generated from."""',
            "",
            "    version: str",
            "    sha256: str",
            "",
            "",
            "@dataclass(frozen=True, slots=True)",
            "class Operation:",
            '    """One operation, as the contract describes it."""',
            "",
            "    method: str",
            "    path: str",
            "    credentials: tuple[str, ...]",
            "    scopes: MappingProxyType[str, tuple[str, ...]]",
            "    issues: str | None",
            "    idempotency_key: bool",
            '    retry: Literal["repeatable", "repeatable-with-key", "once"]',
            "    path_params: tuple[str, ...]",
            "    query_params: tuple[str, ...]",
            "",
            "",
            f"CONTRACT: Final = Contract(version={derived['from']['version']!r}, "
            f"sha256={derived['from']['sha256']!r})",
            '"""The contract this SDK was generated from."""',
            "",
            f"SERVER_PATH: Final = {server_path!r}",
            '"""The path every operation is relative to, from the contract\'s `servers` entry."""',
            "",
            f"DEVELOPER_SCHEMES: Final = {tuple(derived['developerSchemes'])!r}",
            '"""The schemes a developer credential is sent under."""',
            "",
            f"type OperationId = Literal[{operation_ids}]",
            "",
            "OPERATIONS: Final[MappingProxyType[OperationId, Operation]] = MappingProxyType({",
            *entries,
            "})",
            '"""Every operation this SDK covers, derived from the contract by one rule: every',
            "operation whose `security` admits a developer credential, plus the operation a",
            "developer credential's scheme names in `x-atlas-issued-by`.",
            '"""',
            "",
            f"type KnownErrorCode = Literal[{codes}]",
            "",
            f"ERROR_CODES: Final[tuple[KnownErrorCode, ...]] = ({codes},)",
            '"""Every `errorCode` the covered surface documents."""',
            "",
        ]
    )
    return ruff_format(text, "surface.py")


def main() -> int:
    surface_text = SURFACE.read_text(encoding="utf-8")
    surface = json.loads(surface_text)
    derived = surface["x-atlas-derived"]
    files = {
        "__init__.py": '"""Generated from the ATLAS API contract. Do not edit."""\n',
        "contract.py": contract_types(derived),
        "surface.py": surface_constants(surface, surface_text),
    }

    if "--check" in sys.argv[1:]:
        stale = [
            name
            for name, text in files.items()
            if not (OUT / name).exists()
            or (OUT / name).read_text(encoding="utf-8").replace("\r\n", "\n") != text
        ]
        if stale:
            print(
                f"generate: _generated/{' and '.join(stale)} not what the surface generates. "
                "Run: uv run python scripts/generate.py",
                file=sys.stderr,
            )
            return 1
        print(f"generate: _generated/ is current for contract {derived['from']['version']}.")
        return 0

    OUT.mkdir(parents=True, exist_ok=True)
    for name, text in files.items():
        (OUT / name).write_text(text, encoding="utf-8", newline="\n")
    print(
        f"generate: wrote _generated/ - {len(derived['operations'])} operations, "
        f"contract {derived['from']['version']}, {GENERATOR} {version(GENERATOR)}."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
